name: Run Tests

on:
  push:
    branches: [ pre-release, release ]
  pull_request:
    branches: [ pre-release, release ]

jobs:
  run-tests:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Compile files
        run: npm run pretest

      - name: Run tests
        run: npm run test:ci

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-reports
          path: out-test/reports/*.json
          if-no-files-found: error