name: Run Linter

on:
  push:
    branches: [ pre-release, release ]
  pull_request:
    branches: [ pre-release, release ]

jobs:
  lint-javascript:
    name: Lint JavaScript Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Codebase
        uses: jrcligny/run-eslint-action@v1
        with:
          pattern: 'src/**/*.ts'
          overrideConfigFile: eslint.config.mjs